version: "3"
services:
  video-storage:
    image: video-storage
    build:
      context: ./video-storage
      dockerfile: Dockerfile
    container_name: video-storage
    ports:
      - "4000:80"
    environment:
      - PORT=80
      - ACCOUNT_KEY_ID=${ACCOUNT_KEY_ID}
      - ACCOUNT_KEY_SECRET=${ACCOUNT_KEY_SECRET}
    restart: "no"

  video-streaming:
    image: video-streaming
    build:
      context: ./video-streaming
      dockerfile: Dockerfile
    container_name: video-streaming
    ports:
      - "4001:80"
    environment:
      - PORT=80
      - VIDEO_STORAGE_HOST=video-storage
      - VIDEO_STORAGE_PORT=80
    restart: "no"
