version: "3"
services:
  db:
    image: mongo:latest
    container_name: db
    ports:
      - "4000:27017"
    restart: "always"

  rabbit:
    image: rabbitmq:3-management
    container_name: rabbit
    ports:
      - "15672:15672"
      - "5672:5672"
    restart: "always"

  video-storage:
    image: video-storage
    build:
      context: ./video-storage
      dockerfile: Dockerfile-dev
    container_name: video-storage
    volumes:
      - /tmp/video-storage/npm-cache:/root/.npm:z
      - ./video-storage/src:/usr/src/app/src:z
    ports:
      - "4001:80"
    environment:
      - PORT=80
      - ACCOUNT_KEY_ID=${ACCOUNT_KEY_ID}
      - ACCOUNT_SECRET=${ACCOUNT_SECRET}
    restart: "no"

  video-streaming:
    image: video-streaming
    build:
      context: ./video-streaming
      dockerfile: Dockerfile-dev
    container_name: video-streaming
    volumes:
      - /tmp/video-streaming/npm-cache:/root/.npm:z
      - ./video-streaming/src:/usr/src/app/src:z
    ports:
      - "4002:80"
    environment:
      - PORT=80
      - DB_HOST=mongodb://db:27017
      - DB_NAME=video-streaming
      - VIDEO_STORAGE_HOST=video-storage
      - VIDEO_STORAGE_PORT=80
      - RABBIT=amqp://guest:guest@rabbit:5672
    depends_on:
      - db
      - rabbit
    restart: "no"

  history:
    image: history
    build:
      context: ./history
      dockerfile: Dockerfile-dev
    container_name: history
    volumes:
      - /tmp/history/npm-cache:/root/.npm:z
      - ./history/src:/usr/src/app/src:z
    ports:
      - "4003:80"
    environment:
      - PORT=80
      - DB_HOST=mongodb://db:27017
      - DB_NAME=history
      - NODE_ENV=development
      - RABBIT=amqp://guest:guest@rabbit:5672
    depends_on:
      - db
      - rabbit
    restart: "no"
