version: "3"
services:
  db:
    image: mongo:latest
    container_name: db
    ports:
      - "4000:27017"
    restart: "always"

  video-storage:
    image: video-storage
    build:
      context: ./video-storage
      dockerfile: Dockerfile
    container_name: video-storage
    ports:
      - "4001:80"
    environment:
      - PORT=80
      - ACCOUNT_KEY_ID=${ACCOUNT_KEY_ID}
      - ACCOUNT_SECRET=${ACCOUNT_SECRET}
    restart: "no"

  video-streaming:
    image: video-streaming
    build:
      context: ./video-streaming
      dockerfile: Dockerfile
    container_name: video-streaming
    ports:
      - "4002:80"
    environment:
      - PORT=80
      - DB_HOST=mongodb://db:27017
      - DB_NAME=video-streaming
      - VIDEO_STORAGE_HOST=video-storage
      - VIDEO_STORAGE_PORT=80
    restart: "no"
